services:
  privia:
    image: 'ghcr.io/kanak98/privia:latest'
    ports:
      - '${PORT:-3080}:${PORT:-3080}'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.privia.rule=Host(`privia-demo.aiyuuh.com`)"
      - "traefik.http.routers.privia.entrypoints=websecure"
      - "traefik.http.routers.privia.tls.certresolver=letsencrypt"
      - "traefik.http.services.privia.loadbalancer.server.port=3081"
    environment:
      - 'HOST=${HOST:-0.0.0.0}'
      - 'PORT=${PORT:-3080}'
      - 'NODE_ENV=${NODE_ENV:-production}'
      - 'MONGO_URI=${MONGO_URI}'
      - 'DOMAIN_CLIENT=${DOMAIN_CLIENT}'
      - 'DOMAIN_SERVER=${DOMAIN_SERVER}'
      - 'NO_INDEX=${NO_INDEX:-true}'
      - 'TRUST_PROXY=${TRUST_PROXY:-1}'
      - 'DEBUG_LOGGING=${DEBUG_LOGGING:-true}'
      - 'DEBUG_CONSOLE=${DEBUG_CONSOLE:-false}'
      - 'UID=${UID:-1000}'
      - 'GID=${GID:-1000}'
      - 'CONFIG_PATH=${CONFIG_PATH}'
      - 'ENDPOINTS=${ENDPOINTS}'
      - 'PROXY=${PROXY}'
      - 'ANYSCALE_API_KEY=${ANYSCALE_API_KEY}'
      - 'APIPIE_API_KEY=${APIPIE_API_KEY}'
      - 'COHERE_API_KEY=${COHERE_API_KEY}'
      - 'DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}'
      - 'DATABRICKS_API_KEY=${DATABRICKS_API_KEY}'
      - 'FIREWORKS_API_KEY=${FIREWORKS_API_KEY}'
      - 'GROQ_API_KEY=${GROQ_API_KEY}'
      - 'HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}'
      - 'MISTRAL_API_KEY=${MISTRAL_API_KEY}'
      - 'OPENROUTER_KEY=${OPENROUTER_KEY}'
      - 'PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}'
      - 'SHUTTLEAI_API_KEY=${SHUTTLEAI_API_KEY}'
      - 'UNIFY_API_KEY=${UNIFY_API_KEY}'
      - 'XAI_API_KEY=${XAI_API_KEY}'
      - 'PORTKEYIA_API_KEY=${PORTKEYIA_API_KEY}'
      - 'QWEN_API_KEY=${QWEN_API_KEY}'
      - 'TOGETHER_API_KEY=${TOGETHER_API_KEY}'
      - 'NVIDIA_API_KEY=${NVIDIA_API_KEY}'
      - 'KLUSTER_API_KEY=${KLUSTER_API_KEY}'
      - 'SAMBANOVA_API_KEY=${SAMBANOVA_API_KEY}'
      - 'HYPERBOLIC_API_KEY=${HYPERBOLIC_API_KEY}'
      - 'GITHUB_API_KEY=${GITHUB_API_KEY}'
      - 'NANOGPT_API_KEY=${NANOGPT_API_KEY}'
      - 'ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}'
      - 'GOOGLE_KEY=${GOOGLE_KEY}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'DEBUG_OPENAI=${DEBUG_OPENAI:-false}'
      - 'ASSISTANTS_API_KEY=${ASSISTANTS_API_KEY}'
      - 'PLUGIN_MODELS=${PLUGIN_MODELS}'
      - 'DEBUG_PLUGINS=${DEBUG_PLUGINS:-true}'
      - 'CREDS_KEY=${CREDS_KEY}'
      - 'CREDS_IV=${CREDS_IV}'
      - 'FLUX_API_BASE_URL=${FLUX_API_BASE_URL}'
      - 'GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}'
      - 'GOOGLE_CSE_ID=${GOOGLE_CSE_ID}'
      - 'YOUTUBE_API_KEY=${YOUTUBE_API_KEY}'
      - 'SERPAPI_API_KEY=${SERPAPI_API_KEY}'
      - 'SD_WEBUI_URL=${SD_WEBUI_URL}'
      - 'TAVILY_API_KEY=${TAVILY_API_KEY}'
      - 'TRAVERSAAL_API_KEY=${TRAVERSAAL_API_KEY}'
      - 'WOLFRAM_APP_ID=${WOLFRAM_APP_ID}'
      - 'ZAPIER_NLA_API_KEY=${ZAPIER_NLA_API_KEY}'
      - 'SEARCH=${SEARCH:-true}'
      - 'MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}'
      - 'MEILI_HOST=${MEILI_HOST}'
      - 'MEILI_MASTER_KEY=${MEILI_MASTER_KEY}'
      - 'STT_API_KEY=${STT_API_KEY}'
      - 'TTS_API_KEY=${TTS_API_KEY}'
      - 'OPENAI_MODERATION=${OPENAI_MODERATION:-false}'
      - 'OPENAI_MODERATION_API_KEY=${OPENAI_MODERATION_API_KEY}'
      - 'BAN_VIOLATIONS=${BAN_VIOLATIONS:-true}'
      - 'BAN_DURATION=${BAN_DURATION:-7200000}'
      - 'BAN_INTERVAL=${BAN_INTERVAL:-20}'
      - 'LOGIN_VIOLATION_SCORE=${LOGIN_VIOLATION_SCORE:-1}'
      - 'REGISTRATION_VIOLATION_SCORE=${REGISTRATION_VIOLATION_SCORE:-1}'
      - 'CONCURRENT_VIOLATION_SCORE=${CONCURRENT_VIOLATION_SCORE:-1}'
      - 'MESSAGE_VIOLATION_SCORE=${MESSAGE_VIOLATION_SCORE:-1}'
      - 'NON_BROWSER_VIOLATION_SCORE=${NON_BROWSER_VIOLATION_SCORE:-20}'
      - 'LOGIN_MAX=${LOGIN_MAX:-7}'
      - 'LOGIN_WINDOW=${LOGIN_WINDOW:-5}'
      - 'REGISTER_MAX=${REGISTER_MAX:-5}'
      - 'REGISTER_WINDOW=${REGISTER_WINDOW:-60}'
      - 'LIMIT_CONCURRENT_MESSAGES=${LIMIT_CONCURRENT_MESSAGES:-true}'
      - 'CONCURRENT_MESSAGE_MAX=${CONCURRENT_MESSAGE_MAX:-2}'
      - 'LIMIT_MESSAGE_IP=${LIMIT_MESSAGE_IP:-true}'
      - 'MESSAGE_IP_MAX=${MESSAGE_IP_MAX:-40}'
      - 'MESSAGE_IP_WINDOW=${MESSAGE_IP_WINDOW:-1}'
      - 'LIMIT_MESSAGE_USER=${LIMIT_MESSAGE_USER:-false}'
      - 'MESSAGE_USER_MAX=${MESSAGE_USER_MAX:-40}'
      - 'MESSAGE_USER_WINDOW=${MESSAGE_USER_WINDOW:-1}'
      - 'ILLEGAL_MODEL_REQ_SCORE=${ILLEGAL_MODEL_REQ_SCORE:-5}'
      - 'ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN:-true}'
      - 'ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-true}'
      - 'ALLOW_SOCIAL_LOGIN=${ALLOW_SOCIAL_LOGIN:-false}'
      - 'ALLOW_SOCIAL_REGISTRATION=${ALLOW_SOCIAL_REGISTRATION:-false}'
      - 'ALLOW_PASSWORD_RESET=${ALLOW_PASSWORD_RESET:-false}'
      - 'ALLOW_UNVERIFIED_EMAIL_LOGIN=${ALLOW_UNVERIFIED_EMAIL_LOGIN:-true}'
      - 'SESSION_EXPIRY=${SESSION_EXPIRY:-900000}'
      - 'REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY:-604800000}'
      - 'JWT_SECRET=${JWT_SECRET}'
      - 'JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}'
      - 'DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}'
      - 'DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}'
      - 'DISCORD_CALLBACK_URL=${DISCORD_CALLBACK_URL}'
      - 'FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}'
      - 'FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}'
      - 'FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL}'
      - 'GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}'
      - 'GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}'
      - 'GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}'
      - 'GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - 'GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
      - 'GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}'
      - 'APPLE_CLIENT_ID=${APPLE_CLIENT_ID}'
      - 'APPLE_TEAM_ID=${APPLE_TEAM_ID}'
      - 'APPLE_KEY_ID=${APPLE_KEY_ID}'
      - 'APPLE_PRIVATE_KEY_PATH=${APPLE_PRIVATE_KEY_PATH}'
      - 'APPLE_CALLBACK_URL=${APPLE_CALLBACK_URL}'
      - 'OPENID_CLIENT_ID=${OPENID_CLIENT_ID}'
      - 'OPENID_CLIENT_SECRET=${OPENID_CLIENT_SECRET}'
      - 'OPENID_ISSUER=${OPENID_ISSUER}'
      - 'OPENID_SESSION_SECRET=${OPENID_SESSION_SECRET}'
      - 'OPENID_SCOPE=${OPENID_SCOPE}'
      - 'OPENID_CALLBACK_URL=${OPENID_CALLBACK_URL}'
      - 'OPENID_REQUIRED_ROLE=${OPENID_REQUIRED_ROLE}'
      - 'OPENID_REQUIRED_ROLE_TOKEN_KIND=${OPENID_REQUIRED_ROLE_TOKEN_KIND}'
      - 'OPENID_REQUIRED_ROLE_PARAMETER_PATH=${OPENID_REQUIRED_ROLE_PARAMETER_PATH}'
      - 'OPENID_USERNAME_CLAIM=${OPENID_USERNAME_CLAIM}'
      - 'OPENID_NAME_CLAIM=${OPENID_NAME_CLAIM}'
      - 'OPENID_BUTTON_LABEL=${OPENID_BUTTON_LABEL}'
      - 'OPENID_IMAGE_URL=${OPENID_IMAGE_URL}'
      - 'OPENID_AUTO_REDIRECT=${OPENID_AUTO_REDIRECT}'
      - 'OPENID_USE_PKCE=${OPENID_USE_PKCE}'
      - 'OPENID_REUSE_TOKENS=${OPENID_REUSE_TOKENS}'
      - 'OPENID_JWKS_URL_CACHE_ENABLED=${OPENID_JWKS_URL_CACHE_ENABLED}'
      - 'OPENID_JWKS_URL_CACHE_TIME=${OPENID_JWKS_URL_CACHE_TIME}'
      - 'OPENID_ON_BEHALF_FLOW_FOR_USERINFRO_REQUIRED=${OPENID_ON_BEHALF_FLOW_FOR_USERINFRO_REQUIRED}'
      - 'OPENID_ON_BEHALF_FLOW_USERINFRO_SCOPE=${OPENID_ON_BEHALF_FLOW_USERINFRO_SCOPE}'
      - 'OPENID_USE_END_SESSION_ENDPOINT=${OPENID_USE_END_SESSION_ENDPOINT}'
      - 'SAML_ENTRY_POINT=${SAML_ENTRY_POINT}'
      - 'SAML_ISSUER=${SAML_ISSUER}'
      - 'SAML_CERT=${SAML_CERT}'
      - 'SAML_CALLBACK_URL=${SAML_CALLBACK_URL}'
      - 'SAML_SESSION_SECRET=${SAML_SESSION_SECRET}'
      - 'SAML_EMAIL_CLAIM=${SAML_EMAIL_CLAIM}'
      - 'SAML_USERNAME_CLAIM=${SAML_USERNAME_CLAIM}'
      - 'SAML_GIVEN_NAME_CLAIM=${SAML_GIVEN_NAME_CLAIM}'
      - 'SAML_FAMILY_NAME_CLAIM=${SAML_FAMILY_NAME_CLAIM}'
      - 'SAML_PICTURE_CLAIM=${SAML_PICTURE_CLAIM}'
      - 'SAML_NAME_CLAIM=${SAML_NAME_CLAIM}'
      - 'SAML_BUTTON_LABEL=${SAML_BUTTON_LABEL}'
      - 'SAML_IMAGE_URL=${SAML_IMAGE_URL}'
      - EMAIL_FROM=noreply@librechat.ai
      - 'APP_TITLE=${APP_TITLE:-Privia}'
      - 'CUSTOM_FOOTER=${CUSTOM_FOOTER}'
      - 'HELP_AND_FAQ_URL=${HELP_AND_FAQ_URL}'
    depends_on:
      - mongo
  mongo:
    image: 'mongo:6'
    volumes:
      - 'privia-mongo-data:/data/db'
    healthcheck:
      test:
        - CMD
        - mongosh
        - '--eval'
        - "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  privia-mongo-data: {  }
